version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
#   websockets:
#     image: clover/websockets:latest
#     build: ./websockets
#     ports:
#       - "7002:80"
  backend:
    image: clover/backend:latest
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "7001:80"
    depends_on:
      - db
    restart: always
#      - websockets
  frontend:
    image: clover/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "7002:3000"
    restart: always
  nginx:
    image: clover/nginx:latest
    build: ./nginx
    ports:
      - "7080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: always
  #    - websockets


volumes:
  database:
