version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
#   websockets:
#     image: clover/websockets:latest
#     build: ./websockets
#     ports:
#       - "7002:80"
  backend:
    image: clover/backend:latest
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "7001:80"
    depends_on:
      - db
#      - websockets
  frontend:
    image: clover/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "7002:3000"
  nginx:
    image: clover/nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  #    - websockets


volumes:
  database:
