version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
  websockets:
    image: clover/websockets:latest
    build: ./websockets
    ports:
      - "7002:80"
  backend:
    image: clover/backend:latest
    build: ./backend2
    volumes:
      - ./backend2:/app
    ports:
      - "7001:80"
    depends_on:
      - db
      - websockets
  # frontend:
  #   image: clover/frontend:latest
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "7000:80"
  nginx:
    image: clover/nginx:latest
    build: .
    ports:
      - "7080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      # - frontend
      - websockets


volumes:
  database:
