version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  websockets:
    image: clover/websockets:latest
    build: ./websockets
    ports:
      - "7002:80"
    restart: always
  backend:
    image: clover/backend:latest
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "7001:80"
    depends_on:
      - db
      - websockets
    restart: always
  nginx:
    image: clover/nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/static:/frontend/static
      - ./frontend/build:/frontend/build
    depends_on:
      - backend
      - websockets
    restart: always
  cron:
    image: clover/cron:latest
    build: ./cron
    depends_on:
      - nginx
    restart: always


volumes:
  database:
