# Generated by Django 4.0.4 on 2022-06-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
